# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import webbrowser

from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess
import os
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("BURN IT")
        Form.resize(350, 41)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BURN = QtWidgets.QPushButton(Form)
        self.BURN.setObjectName("BURN")
        self.horizontalLayout.addWidget(self.BURN)
        self.OPEN = QtWidgets.QPushButton(Form)
        self.OPEN.setObjectName("OPEN")
        self.horizontalLayout.addWidget(self.OPEN)
        self.BURN.clicked.connect(self.burnit) 
        self.OPEN.clicked.connect(self.loadit)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BURN IT"))
        self.BURN.setText(_translate("Form", "BURN"))
        self.OPEN.setText(_translate("Form", "OPEN"))
    def burnit(self):
        # 
        global_l =os.path.dirname(__file__)

        subprocess.Popen('python '+global_l+'\\itemsearch\\manage.py runserver')
    def loadit(self):
        webbrowser.open('http://127.0.0.1:8000/')
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
